import { index, integer, pgTable, uniqueIndex, uuid, varchar } from 'drizzle-orm/pg-core';
import { createdAtColumn, idColumn } from '../_common.js';
import { contentItems } from './content-items.js';

/**
 * Structural fingerprint used by duplicate detection.
 *
 * A ContentItem may have multiple fingerprints generated by different
 * algorithms. Initial logical algorithm vocabulary: SHA256, SIMHASH,
 * MINHASH, EMBEDDING.
 *
 * The physical representation of an embedding fingerprint may require a
 * later specialization; DB v1 does not assume identical storage
 * semantics beyond this contract.
 *
 * Primary lookup is `(algorithm, fingerprint_value)`.
 *
 * @see DATABASE_SCHEMA_CONTRACT.md §5.16
 */
export const contentFingerprints = pgTable(
  'content_fingerprints',
  {
    id: idColumn(),
    contentItemId: uuid('content_item_id')
      .notNull()
      .references(() => contentItems.id, { onDelete: 'cascade' }),
    algorithm: varchar('algorithm', { length: 64 }).notNull(),
    fingerprintValue: varchar('fingerprint_value', { length: 512 }).notNull(),
    normalizedLength: integer('normalized_length').notNull(),
    createdAt: createdAtColumn(),
  },
  (table) => [
    uniqueIndex('content_fingerprints_item_alg_value_uq').on(
      table.contentItemId,
      table.algorithm,
      table.fingerprintValue,
    ),
    index('content_fingerprints_alg_value_idx').on(table.algorithm, table.fingerprintValue),
    index('content_fingerprints_content_id_idx').on(table.contentItemId),
  ],
);
