packages:
  - 'apps/*'
  - 'packages/*'

overrides:
  drizzle-orm: 0.45.2
  drizzle-kit: 0.31.10
  typescript: 7.0.2
  bullmq: 5.34.0
  ioredis: 5.4.2

allowBuilds:
  esbuild: true
  msgpackr-extract: true
